import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import TRPCProvider from '@/app/_trpc/Provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <TRPCProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="flex h-16 items-center justify-between gap-4 p-4">
              {/* Logo and title */}
              <div className="flex items-center gap-1.5">
                <img src="/toolbench.png" alt="ToolBench Logo" style={{ width: 56, height: 56, display: 'block' }} />
                <span
                  style={{
                    fontSize: 28,
                    fontWeight: 700,
                    color: 'white',
                    textShadow: '0 2px 8px rgba(0,0,0,0.04)',
                    letterSpacing: 1,
                    lineHeight: 1,
                    display: 'inline-block',
                    position: 'relative',
                  }}
                >
                  Tool
                  <span style={{ color: 'steelblue' }}>Bench</span>
                </span>
              </div>
              <div className="flex gap-4 items-center">
                <SignedOut>
                  <SignInButton />
                  <SignUpButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </header>
            {children}
          </body>
        </html>
      </TRPCProvider>
    </ClerkProvider>
  )
}